#----------------------------------------------------------------
# Travis-CI Configuration for R Packages
# https://docs.travis-ci.com/user/languages/r
#----------------------------------------------------------------
language: r
sudo: false
cache: packages
warnings_are_errors: false
r_check_args: --as-cran
latex: false

matrix:
  include:
    - os: linux
      r: oldrel
    - os: linux
      r: release
    - os: linux
      r: devel
      env:
      - R_KEEP_PKG_SOURCE=yes
      - _R_S3_METHOD_LOOKUP_BASEENV_AFTER_GLOBALENV_=true
      - _R_S3_METHOD_LOOKUP_USE_TOPENV_AS_DEFENV_=true
    - os: osx
      r: oldrel
      before_install:
        - Rscript -e 'c(physical = parallel::detectCores(logical = FALSE), logical = parallel::detectCores())'
        - Rscript -e 'install.packages("future", type = "source")'
    - os: osx
      r: release
    - os: linux
      r: release
      r_check_args: --no-build-vignettes --no-codoc --no-examples --no-tests --no-manual --ignore-vignettes
      r_packages:
        - covr
      after_success:
        - Rscript -e 'covr::codecov(quiet=FALSE)'
      env: NB='w/ covr' ## Just a label

before_install:
  - Rscript -e 'c(physical = parallel::detectCores(logical = FALSE), logical = parallel::detectCores())'
  - export _R_CHECK_TIMINGS_=0

notifications:
  email:
    on_success: change
    on_failure: change
